version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./Frontend:/app/Frontend
    environment:
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=syed_logistics
      - POSTGRES_USER=syed_user
      - POSTGRES_PASSWORD=syed_password

volumes:
  postgres_data:
